version: '3.8'

services:
  db:
    image: postgres:15
    container_name: video_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: video_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
